-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

-- Vars
local primary_color = "rgba(F06292ee)"   -- Orchis-Pink-Dark accent (#F06292)
local border_color  = "rgba(F0629255)"   -- window border: 1px, deliberately faint
local glow_color    = "rgba(F0629222)"   -- barely-there halo around the focused window

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
	output   = "",
	mode     = "preferred",
	position = "auto",
	scale    = "auto",
})


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal		= "ghostty"
local fileManager	= "thunar"
local menu			= "rofi -show drun"
local music			= "audacious"
local browser		= "zen-browser"
local kolor			= "eyedropper"
local calc			= "qalculate-gtk"

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function ()
	-- ironbar taskbar (replaces the old eww bar; `eww open bar` no longer runs).
	-- The eww daemon stays up purely for the SUPER+A mouse-accel picker.
	-- hl.exec_cmd("hyprpanel")
	hl.exec_cmd("ironbar")
	-- Ghostty quick-terminal daemon (SUPER+Q, see the bind further down).
	-- It MUST run inside a systemd *scope* named app-<app-id>-<tag>.scope:
	-- xdg-desktop-portal derives the app id from the cgroup, and rejects the
	-- GlobalShortcuts request with "An app id is required" otherwise. A bare
	-- `ghostty` from here lands in session-N.scope, and a transient .service
	-- unit is not recognised either -- both were tested, only the scope works.
	-- The packaged app-com.mitchellh.ghostty.service is Type=dbus and fails
	-- whenever another ghostty already owns the bus name, so it is not used.
	hl.exec_cmd(os.getenv("HOME") .. "/bin/ghostty-quick-toggle --start-only")
	hl.exec_cmd("easyeffects --gapplication-service")
	hl.exec_cmd("ghostty --class=com.scratch.ghostty")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("hyprpaper")
	-- Random wallpaper. `hyprctl hyprpaper preload` returns "invalid hyprpaper
	-- request" on hyprpaper 0.8.4, so it's dropped: `wallpaper` loads the image
	-- itself. The retry loop covers the daemon not being up yet after 1s.
	hl.exec_cmd("bash -c 'WP=$(find ~/Pictures/wallpapers -type f | shuf -n1); for i in 1 2 3 4 5; do sleep 1; hyprctl hyprpaper wallpaper \",$WP\" && break; done'")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

--
-- GPU SPECIFIC
--
-- Detected from each card's PCI vendor ID in sysfs, the same way setup-arch.sh
-- picks its VA-API packages. Keeping it dynamic means this file stays portable
-- across machines: nothing vendor-specific is exported on absent hardware.
local gpu = {}
for i = 0, 15 do
	local f = io.open("/sys/class/drm/card" .. i .. "/device/vendor", "r")
	if f then
		local id = f:read("l")
		f:close()
		if id then gpu[id] = true end
	end
end
local amd, intel, nvidia = gpu["0x1002"], gpu["0x8086"], gpu["0x10de"]

-- A session exposes exactly one VA-API driver, so on a hybrid machine the iGPU
-- wins: it decodes video at a fraction of the dGPU's power draw.
if intel then
	-- intel-media-driver, Broadwell (Gen8, 2014) and newer. Older iGPUs need
	-- libva-intel-driver and "i965" here instead.
	hl.env("LIBVA_DRIVER_NAME", "iHD")
elseif amd then
	-- mesa's gallium driver. Pre-GCN (Northern Islands and older) wants "r600".
	hl.env("LIBVA_DRIVER_NAME", "radeonsi")
elseif nvidia then
	-- Requires libva-nvidia-driver, which maps VA-API onto NVDEC. Without that
	-- package installed this var just leaves VA-API broken, falling back to
	-- software decode. NVD_BACKEND=direct is required by 0.0.10 and newer.
	hl.env("LIBVA_DRIVER_NAME", "nvidia")
	hl.env("NVD_BACKEND", "direct")
end

-- mesa deleted its VDPAU state tracker (the mesa-vdpau package no longer exists
-- at all), so VDPAU on AMD/Intel now has to route through libvdpau-va-gl, which
-- re-implements it on top of the VA-API driver selected above.
if amd or intel then
	hl.env("VDPAU_DRIVER", "va_gl")
end

if nvidia then
	-- Only correct when NVIDIA is the *only* GPU: on a hybrid laptop these force
	-- every GL client onto the dGPU instead of letting it idle.
	if not (amd or intel) then
		hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
		hl.env("GBM_BACKEND", "nvidia-drm")
	end
	-- The old WLR_NO_HARDWARE_CURSORS was dropped with wlroots itself; aquamarine
	-- replaced it with cursor:use_cpu_buffer, already defaulting to auto (2).
end

-- Skip compositing entirely and hand a fullscreen window's buffer straight to
-- the display controller. Pairs with general:allow_tearing above and the
-- immediate = true game rules further down.
hl.config({
	render = {
		direct_scanout = 2, -- 0 disable | 1 enable | 2 auto
	},
})

-- Further knobs, left off deliberately:
-- hl.config({ opengl = { nvidia_anti_flicker = false } })   -- default true; costs frames on
--                                                           -- low-end NVIDIA, but flickers
-- hl.config({ render = { new_render_scheduling = true } })  -- claims better FPS when underpowered
-- hl.config({ misc  = { vrr = 3 } })                        -- 0 off | 1 on | 2 fullscreen | 3 fullscreen_game
-- hl.env("AQ_DRM_DEVICES", "/dev/dri/card1:/dev/dri/card0") -- pick/order GPUs on hybrid setups
--

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct:qt6ct")
hl.env("GDK_BACKEND", "wayland")
hl.env("GTK_IM_MODULE", "simple")

local pictures_dir = os.getenv("HOME") .. "/Pictures"
hl.env("XDG_PICTURES_DIR", pictures_dir)
hl.env("HYPRSHOT_DIR", pictures_dir .. "Screenshots")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
	general = {
		gaps_in  = 3,
		gaps_out = 3,

		border_size = 1,

		col = {
			active_border   = { colors = {border_color}, angle = 45 },
			inactive_border = "rgba(00000000)",
		},

		-- Set to true to enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,

		-- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
		allow_tearing = true,

		layout = "scrolling",
		snap = { enabled = false, },
	},

	decoration = {
		rounding       = 8,
		rounding_power = 2,

		-- Change transparency of focused and unfocused windows
		active_opacity   = 1.0,
		inactive_opacity = 0.65,
		dim_inactive = true,
		dim_strength = 0.1,
		dim_special = 0.4,

		shadow = {
			enabled      = false,
			range        = 4,
			render_power = 3,
			color        = "rgba(000000ee)",
		},

		blur = {
			enabled   = true,
			size      = 3,
			passes    = 1,
			vibrancy  = 0.1696,
			xray  = true,
		},
		glow = {
			enabled = true,
			range = 3,
			render_power = 2,
			color = glow_color,
			color_inactive = "rgba(00000000)"
		},
		--		motion_blur = {
		--			enabled = true,
		--			samples = 8
		--		},
	},

	animations = {
		enabled = true,
		workspace_wraparound = true,
	},
	input = {
		repeat_rate = 65,
		repeat_delay = 150
	},
	xwayland = {
		force_zero_scaling = true,
	},
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 2.8, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 2.8, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "specialWorkspace", enabled = true,  speed = 4.0, bezier = "easeOutQuint", style = "slidefadevert" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
	dwindle = {
		preserve_split = true, -- You probably want this
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
	master = {
		new_status = "master",
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
	scrolling = {
		fullscreen_on_one_column = true,
	},
})

----------------
----  MISC  ----
----------------

hl.config({
	misc = {
		force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
	},
})


---------------
---- INPUT ----
---------------

hl.config({
	input = {
		kb_layout  = "es",
		kb_variant = "",
		kb_model   = "",
		kb_options = "",
		kb_rules   = "",

		follow_mouse = 1,

		sensitivity = -0.2, -- -1.0 - 1.0, 0 means no modification.
		accel_profile = "adaptive",

		scroll_factor = 0.5,

		touchpad = {
			natural_scroll = true,
			middle_button_emulation = true,
			clickfinger_behavior = true,
		},
	},
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
	name        = "epic-mouse-v1",
	sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("ghostty --class=com.scratch.ghostty"))
-- Ghostty quick terminal. The id comes from `hyprctl globalshortcuts`; ghostty
-- derives it from its own `keybind = global:super+q=...` trigger, so changing
-- that line in ~/.config/ghostty/config changes the id here too.
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(os.getenv("HOME") .. "/bin/ghostty-quick-toggle"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/eww/scripts/launch.sh")) -- mouse accel profile picker
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd(kolor))
hl.bind(mainMod .. " + masculine", hl.dsp.exec_cmd(calc))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd(music))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd(os.getenv("HOME") .. "/bin/zellij-picker")) -- zellij session picker
hl.bind("CTRL + Print", hl.dsp.exec_cmd("hyprshot -m region"))
hl.bind("Print", hl.dsp.exec_cmd("hyprpicker -a"))
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
	local key = i % 10 -- 10 maps to key 0
	hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
	hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

hl.bind("Pause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

-- volume (AltGr + Up/Down)
hl.bind("MOD5 + up",   hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })
hl.bind("MOD5 + down", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

-- skip tracks (AltGr + Left/Right)
hl.bind("MOD5 + right", hl.dsp.exec_cmd("playerctl next"),     { locked = true })
hl.bind("MOD5 + left",  hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("term"))

hl.window_rule({ match = { class = "^(com.scratch.ghostty)$" }, workspace = "special:term" })
hl.window_rule({ match = { class = "^(com.scratch.ghostty)$" }, float = true })
hl.window_rule({ match = { class = "^(com.scratch.ghostty)$" }, size = { "monitor_w*0.7", "monitor_h*0.6" } })
hl.window_rule({ match = { class = "^(com.scratch.ghostty)$" }, center = true })

hl.window_rule({  match = { class = "CheatBreaker 1.7.10" }, immediate = true, fullscreen = true })
hl.window_rule({  match = { class = "CheatBreaker 1.8.9" }, immediate = true, fullscreen = true })
hl.window_rule({  match = { class = "^Minecraft.*$" }, immediate = true, fullscreen = true })
hl.window_rule({  match = { class = "zen" }, fullscreen = true })

hl.bind(mainMod .. " + R", hl.dsp.submap("resize"))

hl.define_submap("resize", function()
	hl.bind("right", hl.dsp.window.resize({ x = "100", y = "0" }), { repeating = true })
	hl.bind("left",  hl.dsp.window.resize({ x = "-100", y = "0" }), { repeating = true })
	hl.bind("up",    hl.dsp.window.resize({ x = "0", y = "-100" }), { repeating = true })
	hl.bind("down",  hl.dsp.window.resize({ x = "0", y = "100" }), { repeating = true })
	hl.bind("escape", hl.dsp.submap("reset"))
end)

-- Keyboard control for the eww mouse-accel picker (entered by launch.sh)
hl.define_submap("accel", function()
	local nav = os.getenv("HOME") .. "/.config/eww/scripts/nav.sh"
	hl.bind("up",     hl.dsp.exec_cmd(nav .. " move up"))
	hl.bind("k",      hl.dsp.exec_cmd(nav .. " move up"))
	hl.bind("down",   hl.dsp.exec_cmd(nav .. " move down"))
	hl.bind("j",      hl.dsp.exec_cmd(nav .. " move down"))
	hl.bind("Return", hl.dsp.exec_cmd(nav .. " confirm"))
	hl.bind("space",  hl.dsp.exec_cmd(nav .. " confirm"))
	hl.bind("1",      hl.dsp.exec_cmd(nav .. " apply adaptive"))
	hl.bind("a",      hl.dsp.exec_cmd(nav .. " apply adaptive"))
	hl.bind("2",      hl.dsp.exec_cmd(nav .. " apply custom"))
	hl.bind("c",      hl.dsp.exec_cmd(nav .. " apply custom"))
	hl.bind("escape", hl.dsp.exec_cmd(nav .. " cancel"))
	hl.bind("q",      hl.dsp.exec_cmd(nav .. " cancel"))
end)

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

hl.window_rule({
	-- Ignore maximize requests from all apps. You'll probably like this.
	name  = "suppress-maximize-events",
	match = { class = ".*" },

	suppress_event = "maximize",
})

hl.window_rule({
	-- Fix some dragging issues with XWayland
	name  = "fix-xwayland-drags",
	match = {
		class      = "^$",
		title      = "^$",
		xwayland   = true,
		float      = true,
		fullscreen = false,
		pin        = false,
	},

	no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Blur + dim the desktop behind the rofi launcher so its translucent
-- background picks up the same frosted look as the windows.
hl.layer_rule({
	name  = "rofi-blur",
	match = { namespace = "^rofi$" },
	blur         = true,
	ignore_alpha = 0.2,
	dim_around   = true,
})

hl.layer_rule({
	name  = "zellij-picker-blur",
	match = { namespace = "^zellij-picker$" },
	blur         = true,
	ignore_alpha = 0.2,
	dim_around   = true,
})

-- Hyprland-run windowrule
hl.window_rule({
	name  = "move-hyprland-run",
	match = { class = "hyprland-run" },

	move  = "20 monitor_h-120",
	float = true,
})
